apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oauth
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        appUrl: https://10.10.172.60
        callbackPath: /callback
        clientId: a9969b96-904a-4a16-835c-556a276db2f9
        clientSecretRef:
          name: oauth
          namespace: gloo-system
        issuerUrl: "http://10.10.172.60:8080/auth/realms/master/"
        scopes:
        - email
        headers:
          idTokenHeader: jwt
